// CONST FOR ADD CLASSES

export const CLASSES_SUCCESS = "CLASSES_SUCCESS";
export const CLASSES_PENDING = "CLASSES_PENDING";
export const CLASSES_FAILED = "CLASSES_FAILED";

// const for fetch class data
export const FETCH_CLASS_SUCCESS = "FETCH_CLASS_SUCCES";
export const FETCH_CLASS_PENDING = "FETCH_CLASS_PENDING";
export const FETCH_CLASS_FAILED = "FETCH_CLASS_FAILED";
export const FETCH_SECTIONS_SUCCESS = "FETCH_SECTIONS_SUCCESS";

// CONST FOR USER

export const USERS_SECCESS = "USERS_SECCESS";
export const USERS_PENDING = "USERS_PENDING";
export const USERS_ERR = "USERS_ERR";

// const fetch for students

const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";
const FETCH_USERS_ERR = "FETCH_USERS_ERR";

// fetch single class students
const FETCH_SINGLE_CLASS = "FETCH_SINGLE_CLASS";

export {
  FETCH_USERS_ERR,
  FETCH_USERS_PENDING,
  FETCH_USERS_SUCCESS,
  FETCH_SINGLE_CLASS,
};
