// CONST FOR ADD CLASSES

export const ADMIN_SUCCESS = "ADMIN_SUCCESS";
export const ADMIN_PENDING = "ADMIN_PENDING";
export const ADMIN_FAILED = "ADMIN_FAILED";

// const for fetch class data
export const FETCH_MANAGER_SUCCESS = "FETCH_MANAGER_SUCCES";
export const FETCH_MANAGER_PENDING = "FETCH_MANAGER_PENDING";
export const FETCH_MANAGER_FAILED = "FETCH_MANAGER_FAILED";
export const FETCH_SECTIONS_SUCCESS = "FETCH_SECTIONS_SUCCESS";

// CONST FOR USER

export const USERS_SECCESS = "USERS_SECCESS";
export const USERS_PENDING = "USERS_PENDING";
export const USERS_ERR = "USERS_ERR";

// const fetch for students

const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";
const FETCH_USERS_ERR = "FETCH_USERS_ERR";

// delet student

export const DELETE_SUCCESS = "DELETE_SUCCESS";
export  const DELETE_PENDING = "DELETE_PENDING";
export const DELETE_ERR = "DELETE_ERR";

export {
  FETCH_USERS_ERR,
  FETCH_USERS_PENDING,
  FETCH_USERS_SUCCESS,
};
